# Generated by Django 2.1.10 on 2019-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=80)),
                ('store_name', models.CharField(max_length=80)),
                ('address_line1', models.CharField(max_length=80)),
                ('address_line2', models.CharField(max_length=80)),
                ('pin_code', models.IntegerField()),
                ('district', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pan_number', models.CharField(max_length=80)),
                ('gst_number', models.CharField(max_length=80)),
            ],
        ),
    ]
