# Generated by Django 2.1.10 on 2019-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pin_code',
            field=models.CharField(max_length=80),
        ),
    ]
